window.VALTEC_CONFIG = {
  SUPABASE_URL: "https://SEU-PROJETO.supabase.co",
  SUPABASE_PUBLISHABLE_KEY: "sb_publishable_COLE_AQUI",
  WHATSAPP_NUMBER: "5571XXXXXXXXX",
  PHONE_NUMBER: "+55 71 XXXX-XXXX"
};
