import { getSupabase, isSupabaseConfigured } from './supabase.js';

const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const norm=(v)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const money=(v)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const digits=(v)=>String(v||'').replace(/\D/g,'').replace(/^55(?=\d{10,11}$)/,'');
let supabase=null;

async function ready(){injectReports();injectMessaging();if(isSupabaseConfigured())supabase=await getSupabase();await applyRoleVisibility();await appendLeadList();}

function injectReports(){const nav=$('.central-nav');const main=$('.central-main');if(!nav||!main||$('[data-extra-tab="reports"]'))return;const team=$('[data-admin-tab="team"]');const btn=document.createElement('button');btn.dataset.extraTab='reports';btn.innerHTML='📊 Relatórios';nav.insertBefore(btn,team||null);const panel=document.createElement('section');panel.className='admin-tab';panel.dataset.tabPanel='reports';panel.innerHTML=`<div class="section-toolbar"><div><span class="kicker">Relatórios</span><h2>Visão da operação</h2><p class="muted">Indicadores calculados com os dados salvos na Central Valtec.</p></div><button id="refresh-reports" class="btn btn-light">Atualizar</button></div><section class="metric-grid"><article class="metric"><small>Faturamento no mês</small><strong id="report-revenue">R$ 0</strong></article><article class="metric"><small>Serviços concluídos</small><strong id="report-services">0</strong></article><article class="metric"><small>Clientes cadastrados</small><strong id="report-clients">0</strong></article><article class="metric"><small>Orçamentos aprovados</small><strong id="report-approved">0</strong></article></section><div class="admin-grid"><section class="panel"><span class="kicker">Regiões</span><h2>Bairros com mais atendimentos</h2><div id="report-neighborhoods" class="summary-list"></div></section><section class="panel"><span class="kicker">Equipamentos</span><h2>Serviços mais frequentes</h2><div id="report-equipment" class="summary-list"></div></section></div><div class="admin-grid"><section class="panel"><span class="kicker">Peças</span><h2>Itens mais orçados</h2><div id="report-parts" class="summary-list"></div></section><section class="panel"><span class="kicker">Relacionamento</span><h2>Clientes recorrentes</h2><div id="report-recurring" class="summary-list"></div></section></div>`;main.appendChild(panel);btn.addEventListener('click',()=>{$$('[data-admin-tab], [data-extra-tab]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$$('[data-tab-panel]').forEach(x=>x.classList.toggle('active',x.dataset.tabPanel==='reports'));loadReports()});$('#refresh-reports').onclick=loadReports;}

async function loadReports(){if(!supabase){return setList('report-neighborhoods','Entre com um usuário autorizado para carregar os relatórios.')}const now=new Date(),ym=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;const [receipts,orders,clients,quotes,items]=await Promise.all([supabase.from('receipts').select('amount,issued_at'),supabase.from('service_orders').select('id,client_id,equipment,status,completed_at'),supabase.from('clients').select('id,name,neighborhood'),supabase.from('quotes').select('id,status'),supabase.from('quote_items').select('description,quantity')]);if([receipts,orders,clients,quotes,items].some(x=>x.error))return setList('report-neighborhoods','Não foi possível carregar todos os indicadores agora.');const revenue=(receipts.data||[]).filter(r=>String(r.issued_at||'').startsWith(ym)).reduce((a,r)=>a+Number(r.amount||0),0);const monthOrders=(orders.data||[]).filter(o=>o.status==='concluido'&&String(o.completed_at||'').startsWith(ym));$('#report-revenue').textContent=money(revenue);$('#report-services').textContent=monthOrders.length;$('#report-clients').textContent=(clients.data||[]).length;$('#report-approved').textContent=(quotes.data||[]).filter(q=>q.status==='aprovado').length;const cmap=Object.fromEntries((clients.data||[]).map(c=>[c.id,c]));const neighborhoods={},equipment={},recurring={},parts={};(orders.data||[]).forEach(o=>{const c=cmap[o.client_id];if(c?.neighborhood)neighborhoods[c.neighborhood]=(neighborhoods[c.neighborhood]||0)+1;if(o.equipment)equipment[o.equipment]=(equipment[o.equipment]||0)+1;if(c){recurring[c.name]=(recurring[c.name]||0)+1}});(items.data||[]).forEach(i=>{if(i.description)parts[i.description]=(parts[i.description]||0)+Number(i.quantity||1)});renderRank('report-neighborhoods',neighborhoods,'Nenhum bairro com atendimento ainda.');renderRank('report-equipment',equipment,'Nenhum equipamento registrado ainda.');renderRank('report-parts',parts,'As peças aparecem conforme os orçamentos são salvos.');renderRank('report-recurring',Object.fromEntries(Object.entries(recurring).filter(([,n])=>n>1)),'Ainda não há clientes com mais de um atendimento.');}
function renderRank(id,obj,emptyText){const entries=Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,8);$('#'+id).innerHTML=entries.map(([n,c],i)=>`<div class="summary-row"><span>${i+1}. ${esc(n)}</span><strong>${c}</strong></div>`).join('')||`<p class="muted">${esc(emptyText)}</p>`}
function setList(id,text){const el=$('#'+id);if(el)el.innerHTML=`<p class="muted">${esc(text)}</p>`}

async function applyRoleVisibility(){if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await supabase.from('admin_profiles').select('role').eq('user_id',user.id).maybeSingle();const role=data?.role||'';if(role==='marketing'){$$('[data-admin-tab]').forEach(b=>{if(!['dashboard','marketing'].includes(b.dataset.adminTab))b.style.display='none'})}if(role==='operacao'){$('[data-admin-tab="marketing"]')?.style.setProperty('display','none')}}

async function appendLeadList(){const panel=$('[data-tab-panel="marketing"]');if(!panel||$('#marketing-leads-detail'))return;const box=document.createElement('section');box.id='marketing-leads-detail';box.className='panel list-panel';box.innerHTML='<span class="kicker">Contatos do site</span><h2>Solicitações recentes</h2><div id="marketing-leads-list" class="work-list"><div class="empty-state">Carregando contatos…</div></div>';panel.appendChild(box);if(!supabase)return;const {data,error}=await supabase.from('leads').select('*').order('created_at',{ascending:false}).limit(30);if(error)return setList('marketing-leads-list','Não foi possível carregar os contatos.');$('#marketing-leads-list').innerHTML=(data||[]).map(l=>`<div class="work-item"><div class="work-main"><b>${esc(l.customer_name||'Contato')} · ${esc(l.neighborhood||'')}</b><span>${esc(l.equipment||'Equipamento')} · ${esc(Array.isArray(l.problems)?l.problems.join(', '):l.problems||'')}</span></div><div class="work-meta">${esc(l.status||'novo')}</div><div class="work-actions">${l.phone?`<a class="mini-button green" href="https://wa.me/55${digits(l.phone)}" target="_blank" rel="noopener">WhatsApp</a>`:''}</div></div>`).join('')||'<div class="empty-state">Nenhuma solicitação recente.</div>';}

function injectMessaging(){const orderActions=$('#order-form .form-actions');if(orderActions&&!$('#order-whatsapp-tools')){const bar=document.createElement('div');bar.id='order-whatsapp-tools';bar.className='finish-actions';bar.innerHTML='<b>Mensagens rápidas:</b><button type="button" data-msg="confirm">Confirmar visita</button><button type="button" data-msg="way">Estou a caminho</button><button type="button" data-msg="done">Serviço concluído</button>';orderActions.insertAdjacentElement('afterend',bar);$$('[data-msg]',bar).forEach(b=>b.onclick=()=>orderMessage(b.dataset.msg))}const quoteActions=$('.quote-editor .doc-actions');if(quoteActions&&!$('#quote-whatsapp')){const b=document.createElement('button');b.id='quote-whatsapp';b.className='btn btn-light';b.type='button';b.textContent='WhatsApp';b.onclick=quoteMessage;quoteActions.appendChild(b)}const receiptActions=$('[data-tab-panel="receipts"] .doc-actions');if(receiptActions&&!$('#receipt-whatsapp')){const b=document.createElement('button');b.id='receipt-whatsapp';b.className='btn btn-light';b.type='button';b.textContent='Enviar no WhatsApp';b.onclick=receiptMessage;receiptActions.appendChild(b)}}
async function findClientByName(name){if(!supabase)return null;const {data}=await supabase.from('clients').select('name,phone').ilike('name',name.trim()).limit(10);return(data||[]).find(c=>norm(c.name)===norm(name))||data?.[0]||null}
async function orderMessage(kind){const name=$('#order-client').value.trim(),c=await findClientByName(name);if(!c?.phone)return alert('Cadastre o telefone do cliente para enviar a mensagem.');const when=$('#order-scheduled').value?new Date($('#order-scheduled').value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'';const messages={confirm:`Olá, ${c.name}! Aqui é da Valtec Soluções. Seu atendimento${when?' está previsto para '+when:''}. Podemos confirmar?`,way:`Olá, ${c.name}! Aqui é da Valtec Soluções. Já estamos a caminho para o atendimento.`,done:`Olá, ${c.name}! O serviço da Valtec foi concluído. Obrigado pela confiança. Se precisar de algum esclarecimento sobre o atendimento, estamos à disposição.`};openWa(c.phone,messages[kind])}
async function quoteMessage(){const name=$('#quote-client').value.trim(),c=await findClientByName(name);const phone=$('#quote-phone').value||c?.phone;if(!phone)return alert('Informe o telefone do cliente.');openWa(phone,`Olá, ${name||'cliente'}! Seu orçamento da Valtec Soluções está pronto. Número: ${$('#quote-number').value||'orçamento'}. Total: ${$('#grand-total').textContent}. Se tiver qualquer dúvida, estamos à disposição.`)}
async function receiptMessage(){const name=$('#receipt-client').value.trim(),c=await findClientByName(name);if(!c?.phone)return alert('Cadastre o telefone do cliente para enviar o recibo/mensagem.');openWa(c.phone,`Olá, ${c.name}! Seu recibo da Valtec Soluções foi gerado no valor de ${money($('#receipt-value').value)}. Obrigado pela confiança.`)}
function openWa(phone,text){window.open(`https://wa.me/55${digits(phone)}?text=${encodeURIComponent(text)}`,'_blank','noopener')}

document.addEventListener('DOMContentLoaded',()=>setTimeout(ready,50));
