-- Valtec Soluções — schema inicial
-- Compatível com o modelo atual do Supabase em que novas tabelas podem exigir GRANT explícito para a Data API.

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.service_areas (
  id bigint generated by default as identity primary key,
  neighborhood text not null unique,
  priority text not null default 'principal' check (priority in ('principal', 'consulta')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null,
  phone text not null,
  equipment text not null,
  problems text[] not null default '{}',
  description text,
  neighborhood text not null,
  address text,
  reference_point text,
  media_path text,
  source text not null default 'site',
  status text not null default 'novo' check (status in ('novo','contatado','agendado','concluido','arquivado')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists leads_created_at_idx on public.leads(created_at desc);
create index if not exists leads_neighborhood_idx on public.leads(neighborhood);
create index if not exists leads_equipment_idx on public.leads(equipment);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  path text,
  neighborhood text,
  equipment text,
  problem text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_name_created_idx on public.analytics_events(event_name, created_at desc);
create index if not exists analytics_events_neighborhood_idx on public.analytics_events(neighborhood) where neighborhood is not null;

create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null,
  neighborhood text,
  address text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists clients_phone_idx on public.clients(phone);

create table if not exists public.service_orders (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references public.clients(id) on delete set null,
  lead_id uuid references public.leads(id) on delete set null,
  equipment text not null,
  problem text,
  service_description text,
  status text not null default 'aberto' check (status in ('aberto','agendado','em_execucao','concluido','cancelado')),
  scheduled_for timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quotes (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references public.clients(id) on delete set null,
  lead_id uuid references public.leads(id) on delete set null,
  service_order_id uuid references public.service_orders(id) on delete set null,
  title text not null default 'Orçamento Valtec',
  parts_total numeric(12,2) not null default 0,
  labor_amount numeric(12,2) not null default 0,
  original_total numeric(12,2) not null default 0,
  negotiated_total numeric(12,2),
  status text not null default 'rascunho' check (status in ('rascunho','enviado','aprovado','recusado','cancelado')),
  payment_notes text not null default 'As peças são pagas antecipadamente para a compra dos materiais. A mão de obra pode ser paga após a execução ou antecipadamente, se o cliente preferir.',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quote_items (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.quotes(id) on delete cascade,
  description text not null,
  quantity numeric(10,2) not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null default 0 check (unit_price >= 0),
  created_at timestamptz not null default now()
);

create index if not exists quote_items_quote_id_idx on public.quote_items(quote_id);

-- Seed da área principal.
insert into public.service_areas (neighborhood, priority, active) values
  ('Boca do Rio', 'principal', true),
  ('Costa Azul', 'principal', true),
  ('Imbuí', 'principal', true),
  ('Stiep', 'principal', true),
  ('Pituaçu', 'principal', true),
  ('Armação', 'principal', true),
  ('Pituba', 'principal', true)
on conflict (neighborhood) do update set priority = excluded.priority, active = excluded.active;

-- Data API: grants explícitos, necessários em projetos novos que não expõem tabelas automaticamente.
grant select on public.service_areas to anon, authenticated;
grant insert on public.leads to anon, authenticated;
grant insert on public.analytics_events to anon, authenticated;
grant select, insert, update, delete on public.leads to authenticated;
grant select on public.analytics_events to authenticated;
grant select on public.admin_profiles to authenticated;
grant select, insert, update, delete on public.clients to authenticated;
grant select, insert, update, delete on public.service_orders to authenticated;
grant select, insert, update, delete on public.quotes to authenticated;
grant select, insert, update, delete on public.quote_items to authenticated;

-- RLS em todas as tabelas expostas.
alter table public.admin_profiles enable row level security;
alter table public.service_areas enable row level security;
alter table public.leads enable row level security;
alter table public.analytics_events enable row level security;
alter table public.clients enable row level security;
alter table public.service_orders enable row level security;
alter table public.quotes enable row level security;
alter table public.quote_items enable row level security;

-- Perfil de admin: cada usuário autenticado só consegue enxergar o próprio registro.
drop policy if exists "admin can read own profile" on public.admin_profiles;
create policy "admin can read own profile"
on public.admin_profiles for select
to authenticated
using ((select auth.uid()) = user_id and active = true);

-- Bairros podem ser consultados pelo site público.
drop policy if exists "public can read active service areas" on public.service_areas;
create policy "public can read active service areas"
on public.service_areas for select
to anon, authenticated
using (active = true);

-- Leads: visitante pode criar, mas não ler. O status inicial é sempre 'novo'.
drop policy if exists "public can create leads" on public.leads;
create policy "public can create leads"
on public.leads for insert
to anon, authenticated
with check (status = 'novo');

-- Admins podem operar leads.
drop policy if exists "admins can read leads" on public.leads;
create policy "admins can read leads"
on public.leads for select
to authenticated
using (exists (
  select 1 from public.admin_profiles ap
  where ap.user_id = (select auth.uid()) and ap.active = true
));

drop policy if exists "admins can update leads" on public.leads;
create policy "admins can update leads"
on public.leads for update
to authenticated
using (exists (
  select 1 from public.admin_profiles ap
  where ap.user_id = (select auth.uid()) and ap.active = true
))
with check (exists (
  select 1 from public.admin_profiles ap
  where ap.user_id = (select auth.uid()) and ap.active = true
));

drop policy if exists "admins can delete leads" on public.leads;
create policy "admins can delete leads"
on public.leads for delete
to authenticated
using (exists (
  select 1 from public.admin_profiles ap
  where ap.user_id = (select auth.uid()) and ap.active = true
));

-- Métricas: qualquer visitante pode registrar eventos, só admin pode ler.
drop policy if exists "public can create analytics events" on public.analytics_events;
create policy "public can create analytics events"
on public.analytics_events for insert
to anon, authenticated
with check (char_length(event_name) between 1 and 80);

drop policy if exists "admins can read analytics events" on public.analytics_events;
create policy "admins can read analytics events"
on public.analytics_events for select
to authenticated
using (exists (
  select 1 from public.admin_profiles ap
  where ap.user_id = (select auth.uid()) and ap.active = true
));

-- Tabelas exclusivamente administrativas.
drop policy if exists "admins manage clients" on public.clients;
create policy "admins manage clients" on public.clients
for all to authenticated
using (exists (select 1 from public.admin_profiles ap where ap.user_id = (select auth.uid()) and ap.active = true))
with check (exists (select 1 from public.admin_profiles ap where ap.user_id = (select auth.uid()) and ap.active = true));

drop policy if exists "admins manage service orders" on public.service_orders;
create policy "admins manage service orders" on public.service_orders
for all to authenticated
using (exists (select 1 from public.admin_profiles ap where ap.user_id = (select auth.uid()) and ap.active = true))
with check (exists (select 1 from public.admin_profiles ap where ap.user_id = (select auth.uid()) and ap.active = true));

drop policy if exists "admins manage quotes" on public.quotes;
create policy "admins manage quotes" on public.quotes
for all to authenticated
using (exists (select 1 from public.admin_profiles ap where ap.user_id = (select auth.uid()) and ap.active = true))
with check (exists (select 1 from public.admin_profiles ap where ap.user_id = (select auth.uid()) and ap.active = true));

drop policy if exists "admins manage quote items" on public.quote_items;
create policy "admins manage quote items" on public.quote_items
for all to authenticated
using (exists (select 1 from public.admin_profiles ap where ap.user_id = (select auth.uid()) and ap.active = true))
with check (exists (select 1 from public.admin_profiles ap where ap.user_id = (select auth.uid()) and ap.active = true));

-- Bucket privado para fotos e vídeos enviados no formulário.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('lead-media', 'lead-media', false, 20971520, array['image/*','video/*']::text[])
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Visitantes só fazem upload em um caminho público aleatório; não recebem permissão de leitura.
drop policy if exists "public can upload lead media" on storage.objects;
create policy "public can upload lead media"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'lead-media' and name like 'public/%');

-- Admins podem ler e excluir as mídias.
drop policy if exists "admins can read lead media" on storage.objects;
create policy "admins can read lead media"
on storage.objects for select
to authenticated
using (
  bucket_id = 'lead-media'
  and exists (select 1 from public.admin_profiles ap where ap.user_id = (select auth.uid()) and ap.active = true)
);

drop policy if exists "admins can delete lead media" on storage.objects;
create policy "admins can delete lead media"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'lead-media'
  and exists (select 1 from public.admin_profiles ap where ap.user_id = (select auth.uid()) and ap.active = true)
);
